services:
  redis:
    image: redis:7.4.2-alpine3.21
    restart: unless-stopped
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
  postgres:
    image: postgres:16.3-alpine
    container_name: gredis-pg-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: gredis
    volumes:
      - gredis-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  gredis-db: